[package]
name = "mko-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "mko"
path = "src/main.rs"

[dependencies]
clap.workspace = true
mko-core = { path = "../mko-core" }
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
lopdf = "=0.42.0"
predicates.workspace = true
