use std::{collections::HashMap, fs, path::Path};

use cap_std::fs::Dir;

use crate::{
    atomic::{
        AtomicWriteResult, write_new, write_replace_capability_compare_exchange_validated_at_commit,
    },
    clock::SystemClock,
    config_v2::KnowledgeConfigV2,
    error::MkoError,
    lock::{RepositoryMutationLock, StaleRepositoryLockPolicy},
    projection_v2::{
        ProjectionRecoveryV2, ProjectionWriteOutcomeV2, generated_dashboard_entries_v2,
        generated_projection_entries_v2, prepare_projection_recovery_locked_v2,
        render_projection_v2, set_generated_dashboard_digest_locked_v2, write_projection_locked,
    },
    queue_v2::derive_queue_with_projection_health_v2,
    revision_v2::sha256_digest,
};

const GENERATED_FILE_BYTE_LIMIT: u64 = 8 * 1024 * 1024;

const GENERATED_FILES: &[(&str, &str)] = &[
    (
        "HOME.md",
        r#"---
type: dashboard
generated_by: my-knowledge-os
---

# My Knowledge OS

## 검토 대기

![[views/review-queue.base]]

## 승인된 지식

![[views/knowledge-library.base]]

터미널에서는 `mko queue`로 같은 검토 대기열을 확인할 수 있습니다.
"#,
    ),
    (
        "views/review-queue.base",
        r#"filters:
  and:
    - file.inFolder("views/records")
    - 'derived_state != "approved"'
views:
  - type: table
    name: Review Queue
    order:
      - title
      - record_type
      - derived_state
      - domain
      - perspectives
      - current_revision
"#,
    ),
    (
        "views/knowledge-library.base",
        r#"filters:
  and:
    - file.inFolder("views/records")
    - 'record_type == "knowledge"'
    - 'derived_state == "approved"'
properties:
  perspectives:
    displayName: 관점
views:
  - type: table
    name: 전체 지식
    order:
      - title
      - perspectives
      - tags
      - current_revision
  - type: table
    name: 생활
    filters:
      and:
        - 'list(perspectives).contains("life")'
    order:
      - title
      - perspectives
      - tags
      - current_revision
  - type: table
    name: 학습
    filters:
      and:
        - 'list(perspectives).contains("learning")'
    order:
      - title
      - perspectives
      - tags
      - current_revision
  - type: table
    name: 기술
    filters:
      and:
        - 'list(perspectives).contains("technical")'
    order:
      - title
      - perspectives
      - tags
      - current_revision
  - type: table
    name: 프로젝트
    filters:
      and:
        - 'list(perspectives).contains("project")'
    order:
      - title
      - perspectives
      - tags
      - current_revision
  - type: table
    name: 투자
    filters:
      and:
        - 'list(perspectives).contains("investment")'
    order:
      - title
      - perspectives
      - tags
      - current_revision
"#,
    ),
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DashboardOutcomeV2 {
    Created,
    Existing,
    Repaired,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DashboardCanonicalStateV2 {
    Ready,
    Blocked,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DashboardProjectionStateV2 {
    Current,
    RepairRequired,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DashboardFileKindV2 {
    ViewDefinition,
    RecordProjection,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DashboardFileStateV2 {
    Current,
    Missing,
    Stale,
    UserModified,
    Unowned,
    Orphaned,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DashboardFileStatusV2 {
    pub path: String,
    pub kind: DashboardFileKindV2,
    pub manifest_owned: bool,
    pub state: DashboardFileStateV2,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DashboardStatusV2 {
    pub canonical_state: DashboardCanonicalStateV2,
    pub projection_state: DashboardProjectionStateV2,
    pub manifest_owned_drift: bool,
    pub items: Vec<DashboardFileStatusV2>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DashboardResultV2 {
    pub outcome: DashboardOutcomeV2,
    pub generated_files: Vec<String>,
}

enum DashboardRepairActionV2 {
    Create,
    Keep,
    Replace(Vec<u8>),
}

/// Setup-only compatibility facade. It claims the fixed dashboard definitions in the generated
/// manifest and repairs only missing or demonstrably unmodified stale generated bytes.
pub fn ensure_dashboard_v2(repository_root: &Path) -> Result<DashboardResultV2, MkoError> {
    repair_dashboard_v2(repository_root)
}

pub fn inspect_dashboard_v2(repository_root: &Path) -> Result<DashboardStatusV2, MkoError> {
    KnowledgeConfigV2::read(repository_root)?;
    let _lock = RepositoryMutationLock::acquire(
        repository_root,
        "v2 dashboard inspect",
        &SystemClock,
        StaleRepositoryLockPolicy::Preserve,
    )?;
    inspect_dashboard_locked(repository_root)
}

pub fn repair_dashboard_v2(repository_root: &Path) -> Result<DashboardResultV2, MkoError> {
    KnowledgeConfigV2::read(repository_root)?;
    let _lock = RepositoryMutationLock::acquire(
        repository_root,
        "v2 dashboard repair",
        &SystemClock,
        StaleRepositoryLockPolicy::Preserve,
    )?;
    require_real_directory(&repository_root.join("views"))?;
    let existing_entries = generated_dashboard_entries_v2(repository_root)?
        .into_iter()
        .map(|entry| (entry.path, entry.content_digest))
        .collect::<HashMap<_, _>>();
    let mut plan = Vec::with_capacity(GENERATED_FILES.len());
    for (relative, expected) in GENERATED_FILES {
        let expected = expected.as_bytes();
        let path = repository_root.join(relative);
        let actual = read_optional_regular(&path)?;
        let recorded = existing_entries
            .get(*relative)
            .and_then(|digest| digest.as_deref());
        let action = match actual {
            None => DashboardRepairActionV2::Create,
            Some(actual) if actual == expected => DashboardRepairActionV2::Keep,
            Some(actual) if recorded == Some(sha256_digest(&actual).as_str()) => {
                DashboardRepairActionV2::Replace(actual)
            }
            Some(_) => return Err(dashboard_user_modified(relative)),
        };
        plan.push((*relative, expected, action));
    }
    let projection_entries = generated_projection_entries_v2(repository_root)?
        .into_iter()
        .map(|entry| (entry.path, entry.content_digest))
        .collect::<HashMap<_, _>>();
    let (_, canonical_projections) = derive_queue_with_projection_health_v2(repository_root)?;
    let canonical_paths = canonical_projections
        .iter()
        .map(|projection| projection.path.as_str())
        .collect::<std::collections::HashSet<_>>();
    if let Some(orphan) = projection_entries
        .keys()
        .find(|path| !canonical_paths.contains(path.as_str()))
    {
        return Err(dashboard_orphan_projection(orphan));
    }
    let mut projection_plan = Vec::with_capacity(canonical_projections.len());
    for projection in canonical_projections {
        let rendered = render_projection_v2(&projection.expected)?;
        let actual = read_optional_regular(&repository_root.join(&projection.path))?;
        let recorded = projection_entries
            .get(&projection.path)
            .and_then(|digest| digest.as_deref());
        let safe = match actual.as_deref() {
            None => true,
            Some(actual) if actual == rendered.bytes => true,
            Some(actual) => recorded == Some(sha256_digest(actual).as_str()),
        };
        if !safe {
            let actual = actual.as_deref().ok_or_else(|| {
                MkoError::new(
                    "dashboard_snapshot_changed",
                    "an unsafe projection snapshot unexpectedly has no bytes",
                )
            })?;
            let recovery = prepare_projection_recovery_locked_v2(
                repository_root,
                &projection.expected,
                actual,
            )?;
            return Err(dashboard_projection_user_modified(
                &projection.path,
                &recovery,
            ));
        }
        projection_plan.push((projection.path, projection.expected));
    }
    let mut created = false;
    let mut repaired = false;
    let mut generated_files = Vec::new();
    for (relative, expected, action) in plan {
        let path = repository_root.join(relative);
        match action {
            DashboardRepairActionV2::Create => {
                let publication = write_new(&path, expected, |existing| {
                    let bytes = read_regular(existing)?;
                    if bytes == expected {
                        Ok(())
                    } else {
                        Err(dashboard_user_modified(relative))
                    }
                })?;
                created |= publication == AtomicWriteResult::Created;
            }
            DashboardRepairActionV2::Keep => {}
            DashboardRepairActionV2::Replace(actual) => {
                replace_exact(&path, &actual, expected)?;
                repaired = true;
            }
        }
        set_generated_dashboard_digest_locked_v2(
            repository_root,
            relative,
            &sha256_digest(expected),
        )?;
        generated_files.push((*relative).to_owned());
    }
    for (relative, input) in projection_plan {
        let result = write_projection_locked(repository_root, &input)?;
        match result.outcome {
            ProjectionWriteOutcomeV2::Created => created = true,
            ProjectionWriteOutcomeV2::Updated | ProjectionWriteOutcomeV2::Repaired => {
                repaired = true
            }
            ProjectionWriteOutcomeV2::Existing => {}
            ProjectionWriteOutcomeV2::RepairRequired => {
                let recovery = result.recovery.ok_or_else(|| {
                    MkoError::new(
                        "projection_recovery_failed",
                        "a user-modified projection has no recovery artifacts",
                    )
                })?;
                return Err(dashboard_projection_user_modified(&relative, &recovery));
            }
        }
        generated_files.push(relative);
    }
    Ok(DashboardResultV2 {
        outcome: if repaired {
            DashboardOutcomeV2::Repaired
        } else if created {
            DashboardOutcomeV2::Created
        } else {
            DashboardOutcomeV2::Existing
        },
        generated_files,
    })
}

fn inspect_dashboard_locked(repository_root: &Path) -> Result<DashboardStatusV2, MkoError> {
    require_real_directory(&repository_root.join("views"))?;
    let dashboard_entries = generated_dashboard_entries_v2(repository_root)?
        .into_iter()
        .map(|entry| (entry.path, entry.content_digest))
        .collect::<HashMap<_, _>>();
    let mut items = Vec::new();
    for (relative, expected) in GENERATED_FILES {
        let expected = expected.as_bytes();
        let recorded = dashboard_entries
            .get(*relative)
            .and_then(|digest| digest.as_deref());
        let actual = read_optional_regular(&repository_root.join(relative))?;
        let state = match (recorded, actual.as_deref()) {
            (None, _) => DashboardFileStateV2::Unowned,
            (Some(_), None) => DashboardFileStateV2::Missing,
            (Some(recorded), Some(actual))
                if actual == expected && recorded == sha256_digest(actual) =>
            {
                DashboardFileStateV2::Current
            }
            (Some(recorded), Some(actual)) if recorded == sha256_digest(actual) => {
                DashboardFileStateV2::Stale
            }
            (Some(_), Some(_)) => DashboardFileStateV2::UserModified,
        };
        items.push(DashboardFileStatusV2 {
            path: (*relative).to_owned(),
            kind: DashboardFileKindV2::ViewDefinition,
            manifest_owned: recorded.is_some(),
            state,
        });
    }
    let (queue, canonical_projections) = derive_queue_with_projection_health_v2(repository_root)?;
    let mut canonical_projections = canonical_projections
        .into_iter()
        .map(|projection| (projection.path, (projection.stale, projection.expected)))
        .collect::<HashMap<_, _>>();
    for entry in generated_projection_entries_v2(repository_root)? {
        let canonical = canonical_projections.remove(&entry.path);
        let byte_state = match read_optional_regular(&repository_root.join(&entry.path))? {
            None => DashboardFileStateV2::Missing,
            Some(actual)
                if entry.content_digest.as_deref() == Some(sha256_digest(&actual).as_str()) =>
            {
                DashboardFileStateV2::Current
            }
            Some(_) if entry.content_digest.is_some() => DashboardFileStateV2::UserModified,
            Some(_) => DashboardFileStateV2::Stale,
        };
        let state = match canonical.map(|(stale, _)| stale) {
            None => DashboardFileStateV2::Orphaned,
            Some(false) => byte_state,
            Some(true) if byte_state == DashboardFileStateV2::Current => {
                DashboardFileStateV2::Stale
            }
            Some(true) => byte_state,
        };
        items.push(DashboardFileStatusV2 {
            path: entry.path,
            kind: DashboardFileKindV2::RecordProjection,
            manifest_owned: true,
            state,
        });
    }
    for (path, (_, expected)) in canonical_projections {
        let rendered = render_projection_v2(&expected)?;
        let state = match read_optional_regular(&repository_root.join(&path))? {
            None => DashboardFileStateV2::Unowned,
            Some(actual) if actual == rendered.bytes => DashboardFileStateV2::Unowned,
            Some(_) => DashboardFileStateV2::UserModified,
        };
        items.push(DashboardFileStatusV2 {
            path,
            kind: DashboardFileKindV2::RecordProjection,
            manifest_owned: false,
            state,
        });
    }
    items.sort_by(|left, right| left.path.cmp(&right.path));
    let canonical_state = if queue
        .items
        .iter()
        .any(|item| matches!(item.state, crate::json_v2::QueueItemStateV2::Blocked))
    {
        DashboardCanonicalStateV2::Blocked
    } else {
        DashboardCanonicalStateV2::Ready
    };
    let projection_state = if items
        .iter()
        .any(|item| item.state != DashboardFileStateV2::Current)
    {
        DashboardProjectionStateV2::RepairRequired
    } else {
        DashboardProjectionStateV2::Current
    };
    let manifest_owned_drift = items
        .iter()
        .any(|item| item.manifest_owned && item.state != DashboardFileStateV2::Current);
    Ok(DashboardStatusV2 {
        canonical_state,
        projection_state,
        manifest_owned_drift,
        items,
    })
}

fn read_optional_regular(path: &Path) -> Result<Option<Vec<u8>>, MkoError> {
    match fs::symlink_metadata(path) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(MkoError::new("dashboard_read_failed", error.to_string())),
        Ok(metadata) if metadata.file_type().is_file() && !metadata.file_type().is_symlink() => {
            if metadata.len() > GENERATED_FILE_BYTE_LIMIT {
                return Err(MkoError::new(
                    "dashboard_drift",
                    "generated dashboard file exceeds its bounded size limit",
                ));
            }
            fs::read(path)
                .map(Some)
                .map_err(|error| MkoError::new("dashboard_read_failed", error.to_string()))
        }
        Ok(_) => Err(MkoError::new(
            "dashboard_drift",
            "generated dashboard path is not a non-symlink regular file",
        )),
    }
}

fn read_regular(path: &Path) -> Result<Vec<u8>, MkoError> {
    read_optional_regular(path)?.ok_or_else(|| {
        MkoError::new(
            "dashboard_snapshot_changed",
            "generated dashboard disappeared during repair",
        )
    })
}

fn replace_exact(path: &Path, expected: &[u8], replacement: &[u8]) -> Result<(), MkoError> {
    let parent = path
        .parent()
        .ok_or_else(|| MkoError::new("dashboard_repair_failed", "dashboard has no parent"))?;
    let filename = path
        .file_name()
        .ok_or_else(|| MkoError::new("dashboard_repair_failed", "dashboard has no filename"))?;
    let directory = Dir::open_ambient_dir(parent, cap_std::ambient_authority())
        .map_err(|error| MkoError::new("dashboard_repair_failed", error.to_string()))?;
    write_replace_capability_compare_exchange_validated_at_commit(
        &directory,
        Path::new(filename),
        expected,
        replacement,
        || Ok(()),
        || Ok(()),
    )
    .map_err(|error| MkoError::new("dashboard_snapshot_changed", error.message()))
}

fn dashboard_user_modified(relative: &str) -> MkoError {
    MkoError::new(
        "dashboard_user_modified",
        format!(
            "generated dashboard {relative} contains user edits; it was preserved. Move the edit to a user-owned note or restore the generated bytes before retrying `mko dashboard --repair`"
        ),
    )
}

fn dashboard_projection_user_modified(relative: &str, recovery: &ProjectionRecoveryV2) -> MkoError {
    MkoError::new(
        "dashboard_projection_user_modified",
        format!(
            "generated projection {relative} contains user edits and was preserved; recovery artifacts are at {}, {}, and {}. Review the diff and keep or relocate the edit before retrying `mko dashboard --repair`",
            recovery.backup_path.display(),
            recovery.expected_path.display(),
            recovery.diff_path.display(),
        ),
    )
}

fn dashboard_orphan_projection(relative: &str) -> MkoError {
    MkoError::new(
        "dashboard_orphan_projection",
        format!(
            "generated projection {relative} has no canonical Source or Knowledge record; it was preserved and cannot be regenerated by `mko dashboard --repair`"
        ),
    )
}

fn require_real_directory(path: &Path) -> Result<(), MkoError> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| MkoError::new("dashboard_path_invalid", error.to_string()))?;
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return Err(MkoError::new(
            "dashboard_path_invalid",
            "dashboard parent must be a real directory",
        ));
    }
    Ok(())
}
